# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'SVProgressHUD'
  # Pods for AlamofireExample

 pod 'Alamofire'

  target 'AlamofireExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamofireExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
